### ISSUE TITLE
Stops on freeze in AWS Deep Learning AMI.

### ISSUE THREAD

**Issue by abhinavcode** [hanxiao/bert-as-service#175]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x ] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.1 LTS 
- Python version: 3
---

### Running on server stops at freeze
On running on pre-trained model BERT-Base, Uncased
I:VENTILATOR:[__i:__i: 62]:freeze, optimize and export graph, could take a while...
I:GRAPHOPT:[gra:opt: 48]:model config: ./small/bert_config.json
I:GRAPHOPT:[gra:opt: 50]:checkpoint: ./small/bert_model.ckpt
I:GRAPHOPT:[gra:opt: 54]:build graph...
I:GRAPHOPT:[gra:opt:121]:load parameters from checkpoint...
I:GRAPHOPT:[gra:opt:123]:freeze...

On force close throws
Process ForkPoolWorker-2:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/bin/bert-serving-start", line 13, in <module>
    server = BertServer(args)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 66, in __init__
    self.graph_path = pool.apply(optimize_graph, (self.args,))
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/pool.py", line 259, in apply
    return self.apply_async(func, args, kwds).get()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/pool.py", line 638, in get
    self.wait(timeout)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/pool.py", line 635, in wait
    self._event.wait(timeout)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt

**Comment by hanxiao** [comment]
could you provide the `tensorflow` version and `bert-as-service` version number? please fill in the issue form.

**Comment by abhinavcode** [comment]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version: 1.12.0
- Python version: 3.6.5
- `bert-as-service` version: 1.6.6
- CPU model and memory: Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz  mem - 1009432 kB

---

**Comment by abhinavcode** [comment]
It worked 
There was issue with the RAM size
