### ISSUE TITLE
benchmark execution error

### ISSUE THREAD

**Issue by qnamqj** [hanxiao/bert-as-service#185]
### 1、the first error is:
python benchmark.py 

Traceback (most recent call last):
  File "benchmark.py", line 84, in <module>
    server = BertServer(args)
  File "/miniconda3/envs/bert/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 43, in __init__
    self.logger = set_logger(colored('VENTILATOR', 'magenta'), args.verbose)
AttributeError: type object 'args_nt' has no attribute 'verbose'

### 2、the second error is:
then i read the source, find 
  server = BertServer(args)
because some default property in helper.py that not constain in the args, 
so i add this property to the benchmark.py's common object

common = {
    ......

    'verbose': False,
    'tuned_model_dir': None,
    'ckpt_name': 'bert_model.ckpt',
    'config_name': 'bert_config.json',
    'mask_cls_sep': False,
    'priority_batch_size': 16,
    'device_map': []
}

then again exection  `python benchmark.py`, bet get the new error:

I:VENTILATOR:[__i:__i: 62]:freeze, optimize and export graph, could take a while...
I:GRAPHOPT:[gra:opt: 48]:model config: /chinese_L-12_H-768_A-12/bert_config.json
I:GRAPHOPT:[gra:opt: 50]:checkpoint: /chinese_L-12_H-768_A-12/bert_model.ckpt
I:GRAPHOPT:[gra:opt: 54]:build graph...
I:GRAPHOPT:[gra:opt:121]:load parameters from checkpoint...
I:GRAPHOPT:[gra:opt:123]:freeze...
I:GRAPHOPT:[gra:opt:126]:optimize...
I:GRAPHOPT:[gra:opt:134]:write graph to a tmp file: /tmp/tmpf6x979_k
I:VENTILATOR:[__i:__i: 70]:optimized graph is stored at: /tmp/tmpf6x979_k
I:VENTILATOR:[__i:_ru:102]:bind all sockets
I:VENTILATOR:[__i:_ru:106]:open 8 ventilator-worker sockets
I:VENTILATOR:[__i:_ru:109]:start the sink
I:SINK:[__i:_ru:254]:ready
I:VENTILATOR:[__i:_ge:177]:get devices
I:VENTILATOR:[__i:_ge:209]:device map: 
    worker  0 -> gpu  0
    worker  1 -> gpu  1
I:WORKER-0:[__i:_ru:366]:use device gpu: 0, load graph from /tmp/tmpf6x979_k
I:WORKER-1:[__i:_ru:366]:use device gpu: 1, load graph from /tmp/tmpf6x979_k
I:WORKER-0:[__i:gen:393]:ready and listening!
I:WORKER-1:[__i:gen:393]:ready and listening!
num_client: 1
I:VENTILATOR:[__i:_ru:137]:new config request req id: 0 client: b'3a0ce972-0378-4450-8511-fb59ed6b3e0f'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/miniconda3/envs/bert/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/miniconda3/envs/bert/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 88, in run
    self._run()
  File "/miniconda3/envs/bert/lib/python3.6/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/miniconda3/envs/bert/lib/python3.6/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/miniconda3/envs/bert/lib/python3.6/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/miniconda3/envs/bert/lib/python3.6/site-packages/bert_serving/server/zmq_decor.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/miniconda3/envs/bert/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 150, in _run
    **self.status_static}), req_id])
  File "/miniconda3/envs/bert/lib/python3.6/site-packages/zmq/utils/jsonapi.py", line 40, in dumps
    s = jsonmod.dumps(o, **kwargs)
  File "/miniconda3/envs/bert/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/miniconda3/envs/bert/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/miniconda3/envs/bert/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/miniconda3/envs/bert/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'function' is not JSON serializable

### 3、please tell me how to correct exection the benchmark.py

**Comment by hanxiao** [comment]
fyi, this issue are fixed in #188 and the new feature is available since 1.7.0. Please do the following for the upgrade:
```bash
pip install -U bert-serving-server bert-serving-client
```
