### ISSUE TITLE
Error with BERT server

### ISSUE THREAD

**Issue by simonefrancia** [hanxiao/bert-as-service#227]
Hi, 
after installing bert berver with ```pip install bert-serving-server``` I am not able to launch the server anymore. 
Few day ago this command worked, but today an error occurs:

Command:
``` 
bert-serving-start -model_dir multi_cased_L-12_H-768_A-12 -num_worker=12 -max_seq_len=100
```

Error:
```File "/usr/local/bin/bert-serving-start", line 7, in <module>
    from bert_serving.server.cli import main
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/__init__.py", line 286
    logger.error(f'received a wrongly-formatted request (expected 4 frames, got {len(msg)})')```

I am using python3.5 and tf 1.12. 

Thanks

**Comment by kramer425** [comment]
I'm having the same issue.

**Comment by kramer425** [comment]
Still having this issue with current (docker build):
```
Traceback (most recent call last):
  File "/usr/local/bin/bert-serving-start", line 7, in <module>
    from bert_serving.server.cli import main
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/__init__.py", line 286
    logger.error(f'received a wrongly-formatted request (expected 4 frames, got {len(msg)})')
                                                                                           ^
SyntaxError: invalid syntax
```

**Comment by kramer425** [comment]
Thanks, it was an issue with docker's caching.
