### ISSUE TITLE
Getting TypeError when attempting start server

### ISSUE THREAD

**Issue by dhairyadalal** [hanxiao/bert-as-service#290]
Running TensorFlow 1.13.1 and Python 3.6.8. When I try to load the uncased-base model I get the following error

```
usage: /anaconda3/envs/magic/bin/bert-serving-start -model_dir /models/ -num_worker=4
                 ARG   VALUE
__________________________________________________
           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                cors = *
                 cpu = False
          device_map = []
  fixed_embed_length = False
                fp16 = False
 gpu_memory_fraction = 0.5
       graph_tmp_dir = None
    http_max_connect = 10
           http_port = None
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 25
           model_dir = /models/
          num_worker = 4
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556
       prefetch_size = 10
 priority_batch_size = 16
show_tokens_to_client = False
     tuned_model_dir = None
             verbose = False
                 xla = False

I:VENTILATOR:[__i:__i: 66]:freeze, optimize and export graph, could take a while...
I:GRAPHOPT:[gra:opt: 52]:model config: /models/bert_config.json
I:GRAPHOPT:[gra:opt: 55]:checkpoint: /models/bert_model.ckpt
E:GRAPHOPT:[gra:opt:150]:fail to optimize the graph!
Traceback (most recent call last):
  File "/anaconda3/envs/magic/lib/python3.6/site-packages/bert_serving/server/graph.py", line 57, in optimize_graph
    bert_config = modeling.BertConfig.from_dict(json.load(f))
  File "/anaconda3/envs/magic/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/anaconda3/envs/magic/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/anaconda3/envs/magic/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/anaconda3/envs/magic/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /models/bert_config.json; No such file or directory
Traceback (most recent call last):
  File "/anaconda3/envs/magic/bin/bert-serving-start", line 10, in <module>
    sys.exit(main())
  File "/anaconda3/envs/magic/lib/python3.6/site-packages/bert_serving/server/cli/__init__.py", line 5, in main
    server = BertServer(args)
  File "/anaconda3/envs/magic/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 70, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: 'NoneType' object is not iterable
```

**Comment by dhairyadalal** [comment]
nvm, I mis specificed the path.

**Comment by Masum06** [comment]
I had the same error. I had to put:
`bert-serving-start -model_dir tmp/english_L-12_H-768_A-12/ -num_worker=4 `
instead of
`bert-serving-start -model_dir /tmp/english_L-12_H-768_A-12/ -num_worker=4 `
as suggested in the document.

**Comment by Realvincentyuan** [comment]
@Masum06  The dir statement change does not solve the problem. @dhairyadalal  How do you solve the no json file exactly? Can you explain this?

**Comment by Santhilata** [comment]
Downgrading tensorflow to 1.15.0 worked for me.

**Comment by gioipv** [comment]
using '=' after -model_dir worked for me
bert-serving-start -model_dir=tmp/english_L-12_H-768_A-12/ -num_worker=4
