### ISSUE TITLE
zmq.error.ZMQError: Operation not permitted

### ISSUE THREAD

**Issue by NexusLee** [hanxiao/bert-as-service#293]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [YES ] Are you running the latest `bert-as-service`?
* [YES  ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [YES  ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [YES  ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): Dockerfille
- TensorFlow version: 1.12.0
- Python version: 3.5
- `bert-as-service` version:  1.8.6
- GPU model and memory: 
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start -num_worker=1 -model_dir /app/model/chinese_L-12_H-768_A-12
```

Then this issue shows up:
```
I:VENTILATOR:[__i:__i: 66]:freeze, optimize and export graph, could take a while...
I:GRAPHOPT:[gra:opt: 52]:model config: /app/model/chinese_L-12_H-768_A-12/bert_config.json
I:GRAPHOPT:[gra:opt: 55]:checkpoint: /app/model/chinese_L-12_H-768_A-12/bert_model.ckpt
I:GRAPHOPT:[gra:opt: 59]:build graph...
I:GRAPHOPT:[gra:opt:128]:load parameters from checkpoint...
I:GRAPHOPT:[gra:opt:132]:optimize...
I:GRAPHOPT:[gra:opt:140]:freeze...
I:GRAPHOPT:[gra:opt:145]:write graph to a tmp file: /tmp/tmptpgyzj7m
I:VENTILATOR:[__i:__i: 74]:optimized graph is stored at: /tmp/tmptpgyzj7m
I:VENTILATOR:[__i:_ru:118]:bind all sockets
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/__init__.py", line 104, in run
    self._run()
  File "/usr/local/lib/python3.5/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/zmq_decor.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/__init__.py", line 120, in _run
    addr_front2sink = auto_bind(sink)
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/helper.py", line 192, in auto_bind
    socket.bind('ipc://{}'.format(tmp_dir))
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Operation not permitted
```
dockerfile:
```
FROM tensorflow/tensorflow:1.12.0-py3
RUN pip install bert-serving-server

COPY ./ /app
COPY ./entrypoint.sh /app
WORKDIR /app
```
run:
```
docker run -it --rm -p 5555:5555 -p 5556:5556 -v /e/project/docker/python/bert:/app -t bert-as-service sh
```

...

**Comment by zyj008** [comment]
I met the same problem!  
I installed tensorflow-gpu 1.11.0 in anaconda.
After I type the command "bert-serving-start -model ./chinese_L-12_H-768_A-12 -num_worker=2", there comes an error:
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Operation not permitted

**Comment by zyj008** [comment]
I have solved this problem. It may be due to the bad or unstable Internet.  I didn't do anything and the problem fixed by itself.

**Comment by NexusLee** [comment]
@zyj008 不可能吧，你确定没改动什么吗

**Comment by zyj008** [comment]
@NexusLee  我确定我啥也没动，然后它自己就好了。所以我猜可能是网络不稳定唉。我是在实验室服务器上的anaconda上装的，我弄成功的是cpu版本的tensorflow1.11.0，gpu版本tensorflow的我后来没弄。
另外，我在katacoda上测试dockerfile的时候，不会报zmq这个错误，但是会在最后一步 read and listening的时候出不来就卡住了。

**Comment by NexusLee** [comment]
@zyj008 好的，明天我试试 1.11 版本

**Comment by IDIDIR** [comment]
no, the problem is consistently reproduced.
need export to env
TCP_IP = '0.0.0.0'

**Comment by IDIDIR** [comment]
no, the problem is consistently reproduced.
need create dir and export to env
export ZEROMQ_SOCK_TMP_DIR=/tmp/zmq
link: ```https://sanidem.home.blog/tag/docker/```

**Comment by NexusLee** [comment]
@IDIDIR I tried it. I think it's a problem with old tmp dir

**Comment by xiaoxue88** [comment]
i encounter the same problem, how did you guys solved it? help!!!!

**Comment by lelelove1225** [comment]
i solved this at docker option.
I think this problem caused by docker's permission. add privileged docker-option.

**Comment by miemieshizuka** [comment]
> no, the problem is consistently reproduced.
> need create dir and export to env
> export ZEROMQ_SOCK_TMP_DIR=/tmp/zmq
> link: `https://sanidem.home.blog/tag/docker/`

<img width="316" alt="屏幕快照 2020-08-19 10 18 15" src="https://user-images.githubusercontent.com/69880386/90581098-02e8ad00-e1fd-11ea-93cf-88d28a06f6c6.png">
Hi
It seems like the link is a private site.
Can u share the solution here?
