### ISSUE TITLE
not able to start the server

### ISSUE THREAD

**Issue by sariagoudarzvand** [hanxiao/bert-as-service#368]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [Yes ] Are you running the latest `bert-as-service`?
* [Yes ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [No ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [ There was not any answer for that] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): 
- TensorFlow version:1.10
- Python version:
- `bert-as-service` version:  3.6
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start YOUR_SERVER_ARGS
```

and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
bc.encode()
```

Then this issue shows up:
```
E:GRAPHOPT:[gra:opt:150]:fail to optimize the graph!
Traceback (most recent call last):
  File "/home/sgnbx/anaconda3/envs/py3/lib/python3.5/site-packages/bert_serving/server/graph.py", line 57, in optimize_graph
    bert_config = modeling.BertConfig.from_dict(json.load(f))
  File "/home/sgnbx/anaconda3/envs/py3/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/home/sgnbx/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/home/sgnbx/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/sgnbx/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/english_L-12_H-768_A-12/bert_config.json; No such file or directory
Traceback (most recent call last):
  File "/home/sgnbx/anaconda3/envs/py3/bin/bert-serving-start", line 11, in <module>
    sys.exit(main())
  File "/home/sgnbx/anaconda3/envs/py3/lib/python3.5/site-packages/bert_serving/server/cli/__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "/home/sgnbx/anaconda3/envs/py3/lib/python3.5/site-packages/bert_serving/server/__init__.py", line 70, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: 'NoneType' object is not iterable
```
...

**Comment by kapilkd13** [comment]
Hi @sariagoudarzvand as mentioned in your error log, tensorflow can't find your bert_config file. Can you make sure that it is at intended path and rerun again and see if it still throws the error.
`tensorflow.python.framework.errors_impl.NotFoundError: /tmp/english_L-12_H-768_A-12/bert_config.json; No such file or directory
Traceback (most recent call last):`

**Comment by KuzmaNg** [comment]
Hi, I notice one thing.
change the _PATH_ '/tmp/english_L-12_H-768_A-12/' to 'tmp/english_L-12_H-768_A-12/' or './tmp/english_L-12_H-768_A-12/' works well for me.
You might try.

**Comment by xiaopanlyu** [comment]
> Hi, I notice one thing.
> change the _PATH_ '/tmp/english_L-12_H-768_A-12/' to 'tmp/english_L-12_H-768_A-12/' or './tmp/english_L-12_H-768_A-12/' works well for me.
> You might try.

Thank you very much! It works for my code.
