### ISSUE TITLE
On Windows, I got zmq.error:ZMQError: Protocal not supported when executing 'python app.py'

### ISSUE THREAD

**Issue by BruceDai003** [hanxiao/bert-as-service#39]
Your project is awesome. But I'm not sure if it will work on Windows 10 platform. I just cloned your project, and downloaded the BERT pre-trained model. The moment I run `python app.py -model_dir F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12/ -num_worker=4` , I got an error:
```
λ python app.py -model_dir F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12/ -num_worker=4
usage: app.py -model_dir F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12/ -num_worker=4
                 ARG   VALUE
__________________________________________________
      max_batch_size = 256
         max_seq_len = 25
           model_dir = F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12/
          num_worker = 4
       pooling_layer = -2
    pooling_strategy = REDUCE_MEAN
                port = 5555

Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "F:\Work\Github\bert-as-service\service\server.py", line 72, in run
    self.backend.bind('ipc://*')
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:5653)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:10014)
zmq.error.ZMQError: Protocol not supported
```

I have no idea what this zmq is, and I googled, it seems that 'ipc' is not supported on Windows, we should use 'tcp' instead. I tried to just change 'ipc' to 'tcp' on line 72, but still got the similar error:
```
λ python app.py -model_dir F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12/ -num_worker=4
usage: app.py -model_dir F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12/ -num_worker=4
                 ARG   VALUE
__________________________________________________
      max_batch_size = 256
         max_seq_len = 25
           model_dir = F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12/
          num_worker = 4
       pooling_layer = -2
    pooling_strategy = REDUCE_MEAN
                port = 5555

Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "F:\Work\Github\bert-as-service\service\server.py", line 72, in run
    self.backend.bind('tcp://*')
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:5653)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:10014)
zmq.error.ZMQError: Invalid argument
```

Any idea on how to correct this?

**Comment by KevinChen1994** [comment]
I sovled this question. You can check version of your pyzmq, it must >= 17.1.0. you can use conda to install or update this library. Try it!

**Comment by BruceDai003** [comment]
> I sovled this question. You can check version of your pyzmq, it must >= 17.1.0. you can use conda to install or update this library. Try it!

@KevinChen1994 I just tried it, but still not working.

```
pip freeze list
...
pyzmq==17.1.2
requests==2.19.1
scipy==1.1.0
seaborn==0.9.0
six==1.11.0
tensorboard==1.12.0
tensorflow==1.12.0
termcolor==1.1.0
tflearn==0.3.2
urllib3==1.23
Werkzeug==0.14.1
wincertstore==0.2
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

F:\Work\Github\bert-as-service (master)
(pgportfolio) λ python app.py -model_dir F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12\
usage: app.py -model_dir F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12\
                 ARG   VALUE
__________________________________________________
      max_batch_size = 256
         max_seq_len = 25
           model_dir = F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12\
          num_worker = 1
       pooling_layer = -2
    pooling_strategy = REDUCE_MEAN
                port = 5555

Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\pgportfolio\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "F:\Work\Github\bert-as-service\service\server.py", line 72, in run
    self.backend.bind('ipc://*')
  File "zmq\backend\cython\socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq\backend\cython\checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Protocol not supported
```

**Comment by KevinChen1994** [comment]
> > I sovled this question. You can check version of your pyzmq, it must >= 17.1.0. you can use conda to install or update this library. Try it!
> 
> @KevinChen1994 I just tried it, but still not working.
> 
> ```
> pip freeze list
> ...
> pyzmq==17.1.2
> requests==2.19.1
> scipy==1.1.0
> seaborn==0.9.0
> six==1.11.0
> tensorboard==1.12.0
> tensorflow==1.12.0
> termcolor==1.1.0
> tflearn==0.3.2
> urllib3==1.23
> Werkzeug==0.14.1
> wincertstore==0.2
> You are using pip version 9.0.1, however version 18.1 is available.
> You should consider upgrading via the 'python -m pip install --upgrade pip' command.
> 
> F:\Work\Github\bert-as-service (master)
> (pgportfolio) λ python app.py -model_dir F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12\
> usage: app.py -model_dir F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12\
>                  ARG   VALUE
> __________________________________________________
>       max_batch_size = 256
>          max_seq_len = 25
>            model_dir = F:\data\chinese_L-12_H-768_A-12\chinese_L-12_H-768_A-12\
>           num_worker = 1
>        pooling_layer = -2
>     pooling_strategy = REDUCE_MEAN
>                 port = 5555
> 
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "D:\Anaconda3\envs\pgportfolio\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "F:\Work\Github\bert-as-service\service\server.py", line 72, in run
>     self.backend.bind('ipc://*')
>   File "zmq\backend\cython\socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
>   File "zmq\backend\cython\checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
> zmq.error.ZMQError: Protocol not supported
> ```

Maybe pyzmq depend on other library. Try to install libsodium and zeromq. If you success just tell me.

**Comment by BruceDai003** [comment]
@KevinChen1994 , I just installed both of the libraries you mentioned through conda, but still fails.

**Comment by hanxiao** [comment]
Currently, it doesn't support nor be tested on Windows, as Windows doesn't have `ipc` protocol, which is used to communicate between ventilator, worker and sink. 
Quick solution for now would be change all `icp` to valid `tcp` address as @KevinChen1994 suggested.
 
I marked it as a enhancement-feature and will fix it in the next version.

**Comment by s1162276945** [comment]
The same issue, aha.

**Comment by yawenouyang** [comment]
same issue on Linux，MacOs is ok, dont know why..

**Comment by hanxiao** [comment]
for linux/mac there shouldn't be any problem, they support ipc protocol.

as I said, I will run benchmark and then decide whether to replace ipc with tcp for better compatibility on windows. Yet personally, i don't think hosting bert-as-service on a windows server is common.

**Comment by yawenouyang** [comment]
sorry, It's my environmental problem, not about system. thanks for your code again.

**Comment by kouhonglady** [comment]
The same issue on windows.

**Comment by hanxiao** [comment]
this issue is fixed in latest master, Windows and inter-process TCP are now fully supported.
Please do `pip install -U bert-serving-server  bert-serving-client` and retry.

**Comment by kamac** [comment]
Is TCP supposed to work on linux? When client connects, server config response never arrives.

**Comment by allisonyw** [comment]
Hi, 
I have a similar issue but is running on Colab. 
`I:VENTILATOR:[__i:_ru:129]:bind all sockets
I0806 02:49:48.244951 139764003120896 __init__.py:129] bind all sockets
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/__init__.py", line 115, in run
    self._run()
  File "/usr/local/lib/python3.6/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/zmq_decor.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/__init__.py", line 131, in _run
    addr_front2sink = auto_bind(sink)
  File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/helper.py", line 197, in auto_bind
    socket.bind('ipc://{}'.format(tmp_dir))
  File "zmq/backend/cython/socket.pyx", line 555, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Function not implemented
`

**Comment by allisonyw** [comment]
Hi,
I have a similar issue but is running on Colab.
>  I:VENTILATOR:[__i:_ru:129]:bind all sockets
I0806 02:49:48.244951 139764003120896 __init__.py:129] bind all sockets
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/__init__.py", line 115, in run
    self._run()
  File "/usr/local/lib/python3.6/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/zmq_decor.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/__init__.py", line 131, in _run
    addr_front2sink = auto_bind(sink)
  File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/helper.py", line 197, in auto_bind
    socket.bind('ipc://{}'.format(tmp_dir))
  File "zmq/backend/cython/socket.pyx", line 555, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Function not implemented

**Comment by taiguangxing** [comment]
hello, on linux ,I meet such issue, i dont know how to solve this problem.
`                 ARG   VALUE
__________________________________________________
           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                cors = *
                 cpu = False
          device_map = []
       do_lower_case = True
  fixed_embed_length = False
                fp16 = False
 gpu_memory_fraction = 0.5
       graph_tmp_dir = None
    http_max_connect = 10
           http_port = None
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 256
           model_dir = /home/ire/tgx_workplace/bert/chinese_L-12_H-768_A-12/chinese_L-12_H-768_A-12
no_position_embeddings = False
    no_special_token = False
          num_worker = 1
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5557
            port_out = 5558
       prefetch_size = 10
 priority_batch_size = 16
show_tokens_to_client = False
     tuned_model_dir = None
             verbose = False
                 xla = False

I:VENTILATOR:[__i:__i: 67]:freeze, optimize and export graph, could take a while...
I:GRAPHOPT:[gra:opt: 53]:model config: /home/ire/tgx_workplace/bert/chinese_L-12_H-768_A-12/chinese_L-12_H-768_A-12/bert_config.json
I:GRAPHOPT:[gra:opt: 56]:checkpoint: /home/ire/tgx_workplace/bert/chinese_L-12_H-768_A-12/chinese_L-12_H-768_A-12/bert_model.ckpt
I:GRAPHOPT:[gra:opt: 60]:build graph...
I:GRAPHOPT:[gra:opt:132]:load parameters from checkpoint...
I:GRAPHOPT:[gra:opt:136]:optimize...
I:GRAPHOPT:[gra:opt:144]:freeze...
I:GRAPHOPT:[gra:opt:149]:write graph to a tmp file: /tmp/tmpe8mb1__y
I:VENTILATOR:[__i:__i: 75]:optimized graph is stored at: /tmp/tmpe8mb1__y
I:VENTILATOR:[__i:_ru:129]:bind all sockets
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.5/site-packages/bert_serving/server/__init__.py", line 115, in run
    self._run()
  File "/usr/local/python3/lib/python3.5/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/bert_serving/server/zmq_decor.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/bert_serving/server/__init__.py", line 131, in _run
    addr_front2sink = auto_bind(sink)
  File "/usr/local/python3/lib/python3.5/site-packages/bert_serving/server/helper.py", line 203, in auto_bind
    socket.bind('ipc://{}'.format(tmp_dir))
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Permission denied`
