### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi': 'nvidia-smi'

### ISSUE THREAD

**Issue by simonefrancia** [hanxiao/bert-as-service#4]
Hi, 
I am trying to use this repo doing this command, but I have no GPUs locally.

```
>>> python3.6 app.py -num_worker=4 -model_dir ../multilingual_L-12_H-768_A-12/


usage:
app.py -num_worker=4 -model_dir ../multilingual_L-12_H-768_A-12/
parameters: 
batch_size_per_worker = 256
         max_seq_len = 25
           model_dir = ../multilingual_L-12_H-768_A-12/
          num_worker = 4
                port = 5555
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/src/text/BERT/bert-as-service/service/server.py", line 67, in run
    available_gpus = GPUtil.getAvailable(limit=self.num_worker)
  File "/usr/local/lib/python3.6/dist-packages/GPUtil/GPUtil.py", line 123, in getAvailable
    GPUs = getGPUs()
  File "/usr/local/lib/python3.6/dist-packages/GPUtil/GPUtil.py", line 64, in getGPUs
    p = Popen(["nvidia-smi","--query-gpu=index,uuid,utilization.gpu,memory.total,memory.used,memory.free,driver_version,name,gpu_serial,display_active,display_mode", "--format=csv,noheader,nounits"], stdout=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi': 'nvidia-smi'
```

Is it possible to test this without having GPUs? 

Thanks in advance

**Comment by hanxiao** [comment]
hmm...never thought that, as BERT is actually a pretty large and computational intensive model.
but maybe supports CPU is something meaningful for production. I will consider it as a future feature.

**Comment by simonefrancia** [comment]
If I understood well, I am already using BERT using google official repo and feature extractor works also on cpu.

**Comment by simonefrancia** [comment]
Can I also ask if you did include also [SEP] token embedding. 
I saw that you excluded [CLS] token, and you explained well why. 
Thanks

**Comment by hanxiao** [comment]
i will do some refactoring on the service to support cpu.

i will check how [SEP] is used in their paper and original code.

**Comment by simonefrancia** [comment]
It works, thanks!

**Comment by mittenchops** [comment]
The link mentioned here: 
https://github.com/hanxiao/bert-as-service/tree/server-v2 

Seems to 404 now.  I'm trying to run on CPU only and getting:

```
$ docker run --runtime nvidia -dit -p 5555:5555 -p 5556:5556 -v $PATH_MODEL:/model -t bert-as-service $NUM_WORKER

docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=15081 /var/lib/docker/overlay2/f2e715d21e9928c4873f6a27873ad6ac9952bb079d5d8921716be3bb073bf5a7/merged]\\\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown.
```

Which searches are telling me are related to system failing to find NVIDIA drivers properly.

Is there a CPU-only version that currently works?

**Comment by philflav** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi' when running notebooks
