### ISSUE TITLE
Server crash if i use new version server (1.9.7)

### ISSUE THREAD

**Issue by Mekkeliard** [hanxiao/bert-as-service#448]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro (on docker)
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14.0
- Python version: 3.7.4
- `bert-as-service` version:  1.9.7
- GPU model and memory: NVidia GTX-650ti
- CPU model and memory: Intel Core i5 3330

---

### Description

I'm using this command to start the server:

```bash
bert-serving-start -num_worker=1 -http_port 80 -model_dir /model
```

I'm use REST Api (or ZeroMq - i checked in two versions) and trace (from C# client) phrase on russian language: "Спасибо))) Я просто проверял возможность на элементарные ответы))) Надеюсь Иру доделают до совершенства)".
If i use version 1.9.6, then everything works well. 
But if i use version server 1.9.7, then server crash with error.

Please tell me why this is happening?

Then this issue shows up:

```
Process BertWorker-3:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
return fn(*args)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
options, feed_dict, fetch_list, target_list, run_metadata)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: AssertionError:
Traceback (most recent call last):

File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
ret = func(*args)

File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
values = next(generator_state.get_iterator(iterator_id))

File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/__init__.py", line 574, in gen
is_tokenized, self.mask_cls_sep, self.no_special_token))

File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/bert/extract_features.py", line 116, in convert_lst_to_features
assert len(input_ids) == max_seq_length

AssertionError


[[{{node PyFunc}}]]
[[IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/__init__.py", line 520, in run
self._run()
File "/usr/local/lib/python3.6/dist-packages/zmq/decorators.py", line 75, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/zmq/decorators.py", line 75, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/zmq_decor.py", line 27, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/__init__.py", line 541, in _run
for r in estimator.predict(self.input_fn_builder(receivers, tf, sink_token), yield_single_examples=False):
File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 637, in predict
preds_evaluated = mon_sess.run(predictions)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 754, in run
run_metadata=run_metadata)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1252, in run
run_metadata=run_metadata)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1353, in run
raise six.reraise(*original_exc_info)
File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1338, in run
return self._sess.run(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1411, in run
run_metadata=run_metadata)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1169, in run
return self._sess.run(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
run_metadata_ptr)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
feed_dict_tensor, options, run_metadata)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
run_metadata)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: AssertionError:
Traceback (most recent call last):

File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 209, in
 
__call__
ret = func(*args)

File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
values = next(generator_state.get_iterator(iterator_id))

File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/__init__.py", line 574, in gen
is_tokenized, self.mask_cls_sep, self.no_special_token))

File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/bert/extract_features.py", line 116, in convert_lst_to_features
assert len(input_ids) == max_seq_length

AssertionError


[[{{node PyFunc}}]]
[[IteratorGetNext]]
...
```

**Comment by hanxiao** [comment]
sorry this is due to the recent PR from #447 , reverting it now
