### ISSUE TITLE
KeyboardInterrupt

### ISSUE THREAD

**Issue by DavidInWuhanChina** [hanxiao/bert-as-service#476]
>>> from bert_serving.client import BertClient
>>> bc = BertClient(check_length=False)

^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liaodawei/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py", line 108, in __init__
    s_status = self.server_config
  File "/home/liaodawei/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py", line 206, in arg_wrapper
    return func(self, *args, **kwargs)
  File "/home/liaodawei/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py", line 232, in server_config
    return jsonapi.loads(self._recv(req_id).content[1])
  File "/home/liaodawei/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py", line 153, in _recv
    response = self.receiver.recv_multipart()
  File "/home/liaodawei/anaconda3/lib/python3.7/site-packages/zmq/sugar/socket.py", line 475, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 791, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 827, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt

**Comment by tian231825** [comment]
same problem

**Comment by snakelecaps** [comment]
same

**Comment by birdx0810** [comment]
same

**Comment by sheenG** [comment]
same problem, I could only get output:
`
I:VENTILATOR:[__i:_ru:180]:new config request   req id: 1       client: b'55077a73-76c4-4abd-b554-b6283003f1ed'
I:SINK:[__i:_ru:348]:send config        client b'55077a73-76c4-4abd-b554-b6283003f1ed'
I:VENTILATOR:[__i:_ru:196]:new encode request   req id: 2       size: 1 client: b'55077a73-76c4-4abd-b554-b6283003f1ed'
I:WORKER-0:[__i:gen:568]:new job        socket: 0       size: 1 client: b'55077a73-76c4-4abd-b554-b6283003f1ed#2'
I:SINK:[__i:_ru:342]:job register       size: 1 job id: b'55077a73-76c4-4abd-b554-b6283003f1ed#2'
I:WORKER-0:[__i:_ru:543]:job done       size: (1, 768)  client: b'a35b5d60-2ebb-4463-a37f-8d805bdb67fa#2'
I:SINK:[__i:_ru:334]:collect b'EMBEDDINGS' b'a35b5d60-2ebb-4463-a37f-8d805bdb67fa#2' (E:1/T:0/A:1)
I:SINK:[__i:_ru:357]:send back  size: 1 job id: b'a35b5d60-2ebb-4463-a37f-8d805bdb67fa#2'
`
then my program is blocked.

**Comment by sheenG** [comment]
> same problem, I could only get output:
> `I:VENTILATOR:[__i:_ru:180]:new config request req id: 1 client: b'55077a73-76c4-4abd-b554-b6283003f1ed' I:SINK:[__i:_ru:348]:send config client b'55077a73-76c4-4abd-b554-b6283003f1ed' I:VENTILATOR:[__i:_ru:196]:new encode request req id: 2 size: 1 client: b'55077a73-76c4-4abd-b554-b6283003f1ed' I:WORKER-0:[__i:gen:568]:new job socket: 0 size: 1 client: b'55077a73-76c4-4abd-b554-b6283003f1ed#2' I:SINK:[__i:_ru:342]:job register size: 1 job id: b'55077a73-76c4-4abd-b554-b6283003f1ed#2' I:WORKER-0:[__i:_ru:543]:job done size: (1, 768) client: b'a35b5d60-2ebb-4463-a37f-8d805bdb67fa#2' I:SINK:[__i:_ru:334]:collect b'EMBEDDINGS' b'a35b5d60-2ebb-4463-a37f-8d805bdb67fa#2' (E:1/T:0/A:1) I:SINK:[__i:_ru:357]:send back size: 1 job id: b'a35b5d60-2ebb-4463-a37f-8d805bdb67fa#2'`
> then my program is blocked.

if I enter ctrl + c, traceback output is same as @DavidInWuhanChina

**Comment by sheenG** [comment]
I enabled cpu mode, then I got vectors, but gpu mode still doesn't work.
