### ISSUE TITLE
if http_max_connect=10  ,when appear the error as follow the description, 10 times,will appear

### ISSUE THREAD

**Issue by caseware66** [hanxiao/bert-as-service#487]
Traceback (most recent call last):
  File "/home/elasticsearch/cx/BERT-BiLSTM-CRF-NER-master/bert_base/server/http.py", line 58, in encode_query
    'result':bc.encode( text_list,text,is_tokenized=True)}
  File "/home/elasticsearch/cx/BERT-BiLSTM-CRF-NER-master/bert_base/client/__init__.py", line 433, in arg_wrapper
    r = f if isinstance(f, dict) else f(*args, **kwargs)
  File "/home/elasticsearch/cx/BERT-BiLSTM-CRF-NER-master/bert_base/client/__init__.py", line 197, in arg_wrapper
    return func(self, *args, **kwargs)
  File "/home/elasticsearch/cx/BERT-BiLSTM-CRF-NER-master/bert_base/client/__init__.py", line 262, in encode
    self._check_input_lst_lst_str(texts)
  File "/home/elasticsearch/cx/BERT-BiLSTM-CRF-NER-master/bert_base/client/__init__.py", line 380, in _check_input_lst_lst_str
    BertClient._check_input_lst_str(s)
  File "/home/elasticsearch/cx/BERT-BiLSTM-CRF-NER-master/bert_base/client/__init__.py", line 370, in _check_input_lst_str
    'all elements in the list must be non-empty string, but element %d is %s' % (idx, repr(s)))
ValueError: all elements in the list must be non-empty string, but element 0 is ' '

**Comment by colethienes** [comment]
If you're using BERT with Elasticsearch, check out [this repo](https://github.com/koursaros-ai/nboost).
