### ISSUE TITLE
bert serving start can not start right

### ISSUE THREAD

**Issue by ares5221** [hanxiao/bert-as-service#516]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [ ] Are you running the latest `bert-as-service`? yes
* [ ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [ ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ununtu18.04
- TensorFlow installed from (source or binary):binary
- TensorFlow version:1.10
- Python version:3.6
- `bert-as-service` version: 
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start YOUR_SERVER_ARGS
```

and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
bc.encode()
```

Then this issue shows up:

I:VENTILATOR:[__i:__i: 67]:freeze, optimize and export graph, could take a while...
I:GRAPHOPT:[gra:opt: 53]:model config: /home/liujiefei/pythonworkspace/06bertserver/02bertapp/chinese_L-12_H-768_A-12/bert_config.json
I:GRAPHOPT:[gra:opt: 56]:checkpoint: /home/liujiefei/pythonworkspace/06bertserver/02bertapp/chinese_L-12_H-768_A-12/bert_model.ckpt
I:GRAPHOPT:[gra:opt: 60]:build graph...
I:GRAPHOPT:[gra:opt:132]:load parameters from checkpoint...
I:GRAPHOPT:[gra:opt:136]:optimize...
I:GRAPHOPT:[gra:opt:144]:freeze...
I:GRAPHOPT:[gra:opt:149]:write graph to a tmp file: /tmp/tmpuy7sitnv
I:VENTILATOR:[__i:__i: 75]:optimized graph is stored at: /tmp/tmpuy7sitnv
I:VENTILATOR:[__i:_ru:129]:bind all sockets
I:VENTILATOR:[__i:_ru:133]:open 8 ventilator-worker sockets
I:VENTILATOR:[__i:_ru:136]:start the sink
I:SINK:[__i:_ru:306]:ready
I:VENTILATOR:[__i:_ge:222]:get devices
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/liujiefei/.local/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 115, in run
    self._run()
  File "/home/liujiefei/.local/lib/python3.6/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/home/liujiefei/.local/lib/python3.6/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/home/liujiefei/.local/lib/python3.6/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/home/liujiefei/.local/lib/python3.6/site-packages/bert_serving/server/zmq_decor.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/home/liujiefei/.local/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 143, in _run
    device_map = self._get_device_map()
  File "/home/liujiefei/.local/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 228, in _get_device_map
    num_all_gpu = len(GPUtil.getGPUs())
  File "/home/liujiefei/.local/lib/python3.6/site-packages/GPUtil/GPUtil.py", line 102, in getGPUs
    deviceIds = int(vals[i])
ValueError: invalid literal for int() with base 10: 'Failed to initialize NVML: Driver/library version mismatch'
...

**Comment by SlimenBouras** [comment]
same problem here

**Comment by Scarlett796** [comment]
I have the same problem，have you solved it?

**Comment by 18166035475** [comment]
I have the same problem，have you solved it?

**Comment by ares5221** [comment]
> same problem here

try latest version

**Comment by ares5221** [comment]
> I have the same problem，have you solved it?

try latest version
