### ISSUE TITLE
mac启动bert-server报错TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by cat1222** [hanxiao/bert-as-service#522]
I:VENTILATOR:[__i:__i: 67]:freeze, optimize and export graph, could take a while...
E:GRAPHOPT:[gra:opt:154]:fail to optimize the graph!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bert_serving/server/graph.py", line 42, in optimize_graph
    tf = import_tf(verbose=args.verbose)
  File "/usr/local/lib/python3.7/site-packages/bert_serving/server/helper.py", line 186, in import_tf
    tf.logging.set_verbosity(tf.logging.DEBUG if verbose else tf.logging.ERROR)
AttributeError: module 'tensorflow' has no attribute 'logging'
Traceback (most recent call last):
  File "/usr/local/bin/bert-serving-start", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/bert_serving/server/cli/__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "/usr/local/lib/python3.7/site-packages/bert_serving/server/__init__.py", line 71, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: cannot unpack non-iterable NoneType object

**Comment by disooqi** [comment]
I have the same issue here.

**Comment by shikhar42** [comment]
I am still unable to do it. What am I doing wrong?
The path of the folder is:
![image](https://user-images.githubusercontent.com/8600424/76352099-dd1dba80-62e4-11ea-939b-1e7963f0f903.png)

The command I'm running is:

![image](https://user-images.githubusercontent.com/8600424/76352194-050d1e00-62e5-11ea-8bb2-e7a9ad4fdd10.png)

**Comment by ghunkins** [comment]
@shikhar42 looks like you're need a space between your path and `num_workers`.

**Comment by shikhar42** [comment]
@ghunkins thank you for your reply. But when I do that, I get the following error

![image](https://user-images.githubusercontent.com/8600424/76353514-3f77ba80-62e7-11ea-919e-2c55790e3d4d.png)

I was getting this error earlier and when I removed spaces between the path and num_workers, it accepted num_workers as an argument but then it fails with the type error optimizing the graph.

**Comment by ghunkins** [comment]
@shikhar42 It defaults to `gpu` config I believe, add the `-cpu` flag and you should be fine. It's failing on some CUDA configuration, so the CPU should bypass that.

**Comment by shikhar42** [comment]
@ghunkins

**Comment by shikhar42** [comment]
@ghunkins 
![image](https://user-images.githubusercontent.com/8600424/76354506-f3c61080-62e8-11ea-929f-d6abb8521d97.png)

Is this what you mean, or am I doing something wrong?
Thanks

**Comment by shikhar42** [comment]
anyone else facing the same issue?

**Comment by STHSF** [comment]
@shikhar42 you need to initialize your model_dir with the absolute path not the relative path.
