### ISSUE TITLE
zmq.error.ZMQError: Permission denied   

### ISSUE THREAD

**Issue by Williamlizl** [hanxiao/bert-as-service#531]
usage: /home/lbc/.local/bin/bert-serving-start -model_dir /home/lbc/chinese_L-12_H-768_A-12/chinese_L-12_H-768_A-12/ -num_worker=4
                 ARG   VALUE
__________________________________________________
           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                cors = *
                 cpu = False
          device_map = []
       do_lower_case = True
  fixed_embed_length = False
                fp16 = False
 gpu_memory_fraction = 0.5
       graph_tmp_dir = None
    http_max_connect = 10
           http_port = None
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 25
           model_dir = /home/lbc/chinese_L-12_H-768_A-12/chinese_L-12_H-768_A-12/
no_position_embeddings = False
    no_special_token = False
          num_worker = 4
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556
       prefetch_size = 10
 priority_batch_size = 16
show_tokens_to_client = False
     tuned_model_dir = None
             verbose = False
                 xla = False

I:VENTILATOR:[__i:__i: 67]:freeze, optimize and export graph, could take a while...
I:GRAPHOPT:[gra:opt: 53]:model config: /home/lbc/chinese_L-12_H-768_A-12/chinese_L-12_H-768_A-12/bert_config.json
I:GRAPHOPT:[gra:opt: 56]:checkpoint: /home/lbc/chinese_L-12_H-768_A-12/chinese_L-12_H-768_A-12/bert_model.ckpt
I:GRAPHOPT:[gra:opt: 60]:build graph...
I:GRAPHOPT:[gra:opt:132]:load parameters from checkpoint...
I:GRAPHOPT:[gra:opt:136]:optimize...
I:GRAPHOPT:[gra:opt:144]:freeze...
I:GRAPHOPT:[gra:opt:149]:write graph to a tmp file: /tmp/tmp3y2bjz8w
I:VENTILATOR:[__i:__i: 75]:optimized graph is stored at: /tmp/tmp3y2bjz8w
I:VENTILATOR:[__i:_ru:129]:bind all sockets
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/lbc/.local/lib/python3.5/site-packages/bert_serving/server/__init__.py", line 115, in run
    self._run()
  File "/home/lbc/.local/lib/python3.5/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/home/lbc/.local/lib/python3.5/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/home/lbc/.local/lib/python3.5/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/home/lbc/.local/lib/python3.5/site-packages/bert_serving/server/zmq_decor.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/home/lbc/.local/lib/python3.5/site-packages/bert_serving/server/__init__.py", line 131, in _run
    addr_front2sink = auto_bind(sink)
  File "/home/lbc/.local/lib/python3.5/site-packages/bert_serving/server/helper.py", line 203, in auto_bind
    socket.bind('ipc://{}'.format(tmp_dir))
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Permission denied

**Comment by veenasingh** [comment]
I am also getting the same error:

`Traceback (most recent call last):
  File "/usr/local/activepython-3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/python/tf/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 115, in run
    self._run()
  File "/python/tf/lib/python3.6/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/python/tf/lib/python3.6/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/python/tf/lib/python3.6/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/python/tf/lib/python3.6/site-packages/bert_serving/server/zmq_decor.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/python/tf/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 131, in _run
    addr_front2sink = auto_bind(sink)
  File "/python/tf/lib/python3.6/site-packages/bert_serving/server/helper.py", line 203, in auto_bind
    socket.bind('ipc://{}'.format(tmp_dir))
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Permission denied`

Does anyone have a solution for the same?

**Comment by keepWalking** [comment]
same error…… waiting……

**Comment by Seedlingfish** [comment]
I think maybe the model folder has no permission to be written, when i use "sudo chmod -R 777 ", it works.
