### ISSUE TITLE
zmq.error.ZMQError: Function not implemented issue

### ISSUE THREAD

**Issue by aashishsingh2k** [hanxiao/bert-as-service#543]
I am getting the follow error while setting up the bert server on colab (error occurs on both using CPU and GPU):
```
I:GRAPHOPT:[gra:opt: 60]:build graph...
I:GRAPHOPT:[gra:opt:132]:load parameters from checkpoint...
I:GRAPHOPT:[gra:opt:136]:optimize...
I:GRAPHOPT:[gra:opt:144]:freeze...
I:GRAPHOPT:[gra:opt:149]:write graph to a tmp file: /tmp/tmpjgm18t77
tcmalloc: large alloc 1280114688 bytes == 0x5ccba000 @  0x7fcbb91df1e7 0x5929fc 0x7fcb768aa51d 0x50ac25 0x50c5b9 0x508245 0x589471 0x5a067e 0x50d966 0x508245 0x589471 0x5a067e 0x50d966 0x509d48 0x50aa7d 0x50c5b9 0x509d48 0x50aa7d 0x50c5b9 0x509d48 0x50aa7d 0x50c5b9 0x509455 0x595311 0x54a6ff 0x551b81 0x5aa6ec 0x50abb3 0x50c5b9 0x509d48 0x50aa7d
tcmalloc: large alloc 1280114688 bytes == 0xe4ca000 @  0x7fcbb91e1887 0x7fcbb7ad7c29 0x7fcbb7ad7ff2 0x7fcbb7ad865e 0x7fcb7b3c83fc 0x7fcb7b3f7d30 0x50a8af 0x50c5b9 0x509d48 0x50aa7d 0x50c5b9 0x508245 0x589471 0x5a067e 0x50d966 0x508245 0x589471 0x5a067e 0x50d966 0x509d48 0x50aa7d 0x50c5b9 0x509d48 0x50aa7d 0x50c5b9 0x509d48 0x50aa7d 0x50c5b9 0x509455 0x595311 0x54a6ff
I:VENTILATOR:[__i:__i: 75]:optimized graph is stored at: /tmp/tmpjgm18t77
I:VENTILATOR:[__i:_ru:129]:bind all sockets
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/__init__.py", line 115, in run
    self._run()
  File "/usr/local/lib/python3.6/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/zmq_decor.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/__init__.py", line 131, in _run
    addr_front2sink = auto_bind(sink)
  File "/usr/local/lib/python3.6/dist-packages/bert_serving/server/helper.py", line 203, in auto_bind
    socket.bind('ipc://{}'.format(tmp_dir))
  File "zmq/backend/cython/socket.pyx", line 549, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Function not implemented
```

I tried setting up bert on colab using-
```
! pip install -U bert-serving-server bert-serving-client
!bert-serving-start -model_dir /tmp/english_L-12_H-768_A-12/ -num_worker=4 #i give the absolute path here
```
I am using
Current  pyzmq version is 17.1.0
Current libzmq version is 4.2.5
infact the error exists when I upgrade to pyzmq to latest version 19 (latest at the time of writing this post)
I tried looking up other issues but non reflect what I get. Can someone help me with this?

**Comment by wunianjian** [comment]
Hi, I have the same problem. Have you found any solution?
Thank you.

**Comment by aashishsingh2k** [comment]
I couldnt fixed it but this colab notebook runs bert as a service correctly-
https://colab.research.google.com/drive/1Lg92UAzuqSItBLbG9STprz-iiXIlkltQ?usp=sharing
Thanks to Aashik Saibabu for the code

**Comment by wunianjian** [comment]
Thank you for sharing the code. I find that my problem is because I use
```
from google.colab import drive
drive.mount('/content/gdrive')
```
to mount my google drive and then start a server.
But I am still confused, if I can not run the server on my drive, what if I want to serve on the fine-tune model of my own? Maybe the only solution is to upload the model and wget it? Although I still don't understand why I can't run the server after mounting my drive...

**Comment by waghmareomkar** [comment]
i referred [to](url) the solution posted in #526 as an alternate method. worked for me in colab. 
I'm guessing colab has some port issues due to which the server isn't able to setup correctly.

**Comment by svjan5** [comment]
Just do:
`export ZEROMQ_SOCK_TMP_DIR=/tmp/zmq`
