### ISSUE TITLE
TypeError: 'NoneType' object is not iterable -- cannot start the server via command window

### ISSUE THREAD

**Issue by FanyiMo** [hanxiao/bert-as-service#564]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x ] Are you running the latest `bert-as-service`?
* [x ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [ x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- TensorFlow installed from (source or binary): I typed this in command window to install:  pip3 install tensorflow-gpu==1.15
- TensorFlow version: 1.15
- Python version: 3.5
- `bert-as-service` version: the latest version; 
    I typed this in command window to install: pip3 install -U bert-serving-server bert-serving-client
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

**I'm using this command to start the server:** 
bert-serving-start -model_dir /BERT/uncased_L-24_H-1024_A-16 -num_worker=1
```bash
bert-serving-start YOUR_SERVER_ARGS
```
2020-06-10 11:03:25.838138: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
usage: C:\Users\Fanyi Mo\AppData\Local\Programs\Python\Python35\Scripts\bert-serving-start -model_dir /BERT/uncased_L-24_H-1024_A-16 -num_worker=1
                 ARG   VALUE
__________________________________________________
           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                cors = *
                 cpu = False
          device_map = []
       do_lower_case = True
  fixed_embed_length = False
                fp16 = False
 gpu_memory_fraction = 0.5
       graph_tmp_dir = None
    http_max_connect = 10
           http_port = None
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 25
           model_dir = /BERT/uncased_L-24_H-1024_A-16
no_position_embeddings = False
    no_special_token = False
          num_worker = 1
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556
       prefetch_size = 10
 priority_batch_size = 16
show_tokens_to_client = False
     tuned_model_dir = None
             verbose = False
                 xla = False

**Then this issue shows up:**
I:[35mVENTILATOR[0m:freeze, optimize and export graph, could take a while...
2020-06-10 11:03:30.497862: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
WARNING:tensorflow:From c:\users\fanyi mo\appdata\local\programs\python\python35\lib\site-packages\bert_serving\server\helper.py:186: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From c:\users\fanyi mo\appdata\local\programs\python\python35\lib\site-packages\bert_serving\server\helper.py:186: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

I:[36mGRAPHOPT[0m:model config: /BERT/uncased_L-24_H-1024_A-16\bert_config.json
I:[36mGRAPHOPT[0m:checkpoint: /BERT/uncased_L-24_H-1024_A-16\bert_model.ckpt
E:[36mGRAPHOPT[0m:fail to optimize the graph!
Traceback (most recent call last):
  File "c:\users\fanyi mo\appdata\local\programs\python\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\fanyi mo\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Fanyi Mo\AppData\Local\Programs\Python\Python35\Scripts\bert-serving-start.exe\__main__.py", line 7, in <module>
  File "c:\users\fanyi mo\appdata\local\programs\python\python35\lib\site-packages\bert_serving\server\cli\__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "c:\users\fanyi mo\appdata\local\programs\python\python35\lib\site-packages\bert_serving\server\__init__.py", line 71, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: 'NoneType' object is not iterable
...

**Comment by SmartMapple** [comment]
i met the same question, how to solve it

**Comment by geds133** [comment]
I have the same problem, and have tried numerous different model paths to no success

**Comment by Chealkeo** [comment]
> **Prerequisites**
> 
> > Please fill in by replacing `[ ]` with `[x]`.
> 
> * [x ] Are you running the latest `bert-as-service`?
> * [x ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
> * [x ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
> * [ x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?
> 
> **System information**
> 
> > Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
> * TensorFlow installed from (source or binary): I typed this in command window to install:  pip3 install tensorflow-gpu==1.15
> * TensorFlow version: 1.15
> * Python version: 3.5
> * `bert-as-service` version: the latest version;
>   I typed this in command window to install: pip3 install -U bert-serving-server bert-serving-client
> * GPU model and memory:
> * CPU model and memory:
> 
> ### Description
> > Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.
> 
> **I'm using this command to start the server:**
> bert-serving-start -model_dir /BERT/uncased_L-24_H-1024_A-16 -num_worker=1
> 
> ```shell
> bert-serving-start YOUR_SERVER_ARGS
> ```
> 
> 2020-06-10 11:03:25.838138: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
> usage: C:\Users\Fanyi Mo\AppData\Local\Programs\Python\Python35\Scripts\bert-serving-start -model_dir /BERT/uncased_L-24_H-1024_A-16 -num_worker=1
> ARG VALUE
> 
> ```
>        ckpt_name = bert_model.ckpt
>      config_name = bert_config.json
>             cors = *
>              cpu = False
>       device_map = []
>    do_lower_case = True
> ```
> 
> fixed_embed_length = False
> fp16 = False
> gpu_memory_fraction = 0.5
> graph_tmp_dir = None
> http_max_connect = 10
> http_port = None
> mask_cls_sep = False
> max_batch_size = 256
> max_seq_len = 25
> model_dir = /BERT/uncased_L-24_H-1024_A-16
> no_position_embeddings = False
> no_special_token = False
> num_worker = 1
> pooling_layer = [-2]
> pooling_strategy = REDUCE_MEAN
> port = 5555
> port_out = 5556
> prefetch_size = 10
> priority_batch_size = 16
> show_tokens_to_client = False
> tuned_model_dir = None
> verbose = False
> xla = False
> 
> **Then this issue shows up:**
> I:�[35mVENTILATOR�[0m:freeze, optimize and export graph, could take a while...
> 2020-06-10 11:03:30.497862: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
> WARNING:tensorflow:From c:\users\fanyi mo\appdata\local\programs\python\python35\lib\site-packages\bert_serving\server\helper.py:186: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.
> 
> WARNING:tensorflow:From c:\users\fanyi mo\appdata\local\programs\python\python35\lib\site-packages\bert_serving\server\helper.py:186: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.
> 
> I:�[36mGRAPHOPT�[0m:model config: /BERT/uncased_L-24_H-1024_A-16\bert_config.json
> I:�[36mGRAPHOPT�[0m:checkpoint: /BERT/uncased_L-24_H-1024_A-16\bert_model.ckpt
> E:�[36mGRAPHOPT�[0m:fail to optimize the graph!
> Traceback (most recent call last):
> File "c:\users\fanyi mo\appdata\local\programs\python\python35\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "c:\users\fanyi mo\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\Fanyi Mo\AppData\Local\Programs\Python\Python35\Scripts\bert-serving-start.exe__main__.py", line 7, in File "c:\users\fanyi mo\appdata\local\programs\python\python35\lib\site-packages\bert_serving\server\cli__init__.py", line 4, in main
> with BertServer(get_run_args()) as server:
> File "c:\users\fanyi mo\appdata\local\programs\python\python35\lib\site-packages\bert_serving\server__init__.py", line 71, in **init**
> self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
> TypeError: 'NoneType' object is not iterable
> ...

perhaps you could check whether your `model_dir`  path is  correct.
