### ISSUE TITLE
Tensorflow 2.0 AttributeError: module 'tensorflow' has no attribute 'logging'

### ISSUE THREAD

**Issue by MaxNiebergall** [hanxiao/bert-as-service#566]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x ] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): AWS Sagemaker conda_amazonei_tensorflow2_p36 
- TensorFlow installed from (source or binary): preinstalled in Sagemaker
- TensorFlow version: 2.0.2
- Python version: 3.6
- `bert-as-service` version: 1.10.1
- GPU model and memory: none
- CPU model and memory: ml.t2.medium AWS instance

---

### Description

when starting the server I get some errors, it seems like tensorflow 2.0 has done away with tf.logging.
I:VENTILATOR:[__i:__i: 67]:freeze, optimize and export graph, could take a while...
E:GRAPHOPT:[gra:opt:154]:fail to optimize the graph!
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages/bert_serving/server/graph.py", line 42, in optimize_graph
    tf = import_tf(verbose=args.verbose)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages/bert_serving/server/helper.py", line 186, in import_tf
    tf.logging.set_verbosity(tf.logging.DEBUG if verbose else tf.logging.ERROR)
AttributeError: module 'tensorflow' has no attribute 'logging'
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/bert-serving-start", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages/bert_serving/server/cli/__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 71, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: 'NoneType' object is not iterable

I'm using this command to start the server:
!bert-serving-start -model_dir /data/wwm_uncased_L-24_H-1024_A-16/ -num_worker=1

and calling the server via:
N/A

Then this issue shows up:

![image](https://user-images.githubusercontent.com/11083975/84536700-68c82e00-acbc-11ea-943e-61c87eb1a810.png)

**Comment by francisjervis** [comment]
Same issue, trying to run the `run_bert_service.sh` script in this project throws the same error. https://github.com/nghuyong/rasa-faq-bot

**Comment by francisjervis** [comment]
This is apparently fixed in #549
