### ISSUE TITLE
Error starting bert server

### ISSUE THREAD

**Issue by weihangChen** [hanxiao/bert-as-service#583]
Your work is really great, and I am trying to follow the tutorial to get it started.

I am following in the dockerfile, tensorflow version is 1.12
```

FROM tensorflow/tensorflow:1.12.0
WORKDIR /src
COPY src .
RUN apt-get update && apt-get install -y
RUN pip install --upgrade pip
RUN pip install bert-serving-server
RUN pip install bert-serving-client
```

and when I start the server, get following error

```
root@4e601eea10d7:/src# bert-serving-start -model_dir /model/multi_cased_L-12_H-768_A-12/ -num_worker=1
Traceback (most recent call last):
  File "/usr/local/bin/bert-serving-start", line 5, in <module>
    from bert_serving.server.cli import main
  File "/usr/local/lib/python2.7/dist-packages/bert_serving/server/__init__.py", line 191
    sink.send_multipart([client, msg, jsonapi.dumps({**status_runtime,
                                                      ^
SyntaxError: invalid syntax

```

seems to be a similar error as here https://github.com/hanxiao/bert-as-service/issues/227

Thanks
Marc

**Comment by weihangChen** [comment]
it is my bad, python2.7 is used in server and it is clearly stated in the documentation.

following dockerfile works


```
FROM ubuntu:18.04
WORKDIR /src
COPY src .
RUN apt-get update && apt-get install -y python3.6 && apt-get install -y python3-pip
RUN pip3 install tensorflow==1.12.0
RUN pip3 install bert-serving-server
RUN pip3 install bert-serving-client
```
