### ISSUE TITLE
Tensorflow 2.3.0

### ISSUE THREAD

**Issue by fiego** [hanxiao/bert-as-service#587]
2020-09-02 10:03:25.990101: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
c:\programdata\anaconda3\lib\site-packages\bert_serving\server\helper.py:175: UserWarning: Tensorflow 2.3.0 is not tested! It may or may not work. Feel free to submit an issue at
 https://github.com/hanxiao/bert-as-service/issues/
  warnings.warn('Tensorflow %s is not tested! It may or may not work. '
E:?[36mGRAPHOPT?[0m:fail to optimize the graph!
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\bert-serving-start.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\bert_serving\server\cli\__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "c:\programdata\anaconda3\lib\site-packages\bert_serving\server\__init__.py", line 71, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: cannot unpack non-iterable NoneType object

请问这个问题怎么解决

**Comment by py-wen-song** [comment]
> 2020-09-02 10:03:25.990101: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> c:\programdata\anaconda3\lib\site-packages\bert_serving\server\helper.py:175: UserWarning: Tensorflow 2.3.0 is not tested! It may or may not work. Feel free to submit an issue at
> https://github.com/hanxiao/bert-as-service/issues/
> warnings.warn('Tensorflow %s is not tested! It may or may not work. '
> E:?[36mGRAPHOPT?[0m:fail to optimize the graph!
> Traceback (most recent call last):
> File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\ProgramData\Anaconda3\Scripts\bert-serving-start.exe__main__.py", line 7, in File "c:\programdata\anaconda3\lib\site-packages\bert_serving\server\cli__init__.py", line 4, in main with BertServer(get_run_args()) as server: File "c:\programdata\anaconda3\lib\site-packages\bert_serving\server__init__.py", line 71, in **init**
> self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
> TypeError: cannot unpack non-iterable NoneType object
> 
> 请问这个问题怎么解决

使用Tensorflow1的版本就没问题，目前我是这样解决的，没有去修改代码

**Comment by esra-aydemir** [comment]
> > 2020-09-02 10:03:25.990101: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> > c:\programdata\anaconda3\lib\site-packages\bert_serving\server\helper.py:175: UserWarning: Tensorflow 2.3.0 is not tested! It may or may not work. Feel free to submit an issue at
> > https://github.com/hanxiao/bert-as-service/issues/
> > warnings.warn('Tensorflow %s is not tested! It may or may not work. '
> > E:?[36mGRAPHOPT?[0m:fail to optimize the graph!
> > Traceback (most recent call last):
> > File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\ProgramData\Anaconda3\Scripts\bert-serving-start.exe__main__.py", line 7, in File "c:\programdata\anaconda3\lib\site-packages\bert_serving\server\cli__init__.py", line 4, in main with BertServer(get_run_args()) as server: File "c:\programdata\anaconda3\lib\site-packages\bert_serving\server__init__.py", line 71, in **init**
> > self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
> > TypeError: cannot unpack non-iterable NoneType object
> > 请问这个问题怎么解决
> 
> 使用Tensorflow1的版本就没问题，目前我是这样解决的，没有去修改代码

Which version did you downgrade to? I tried 1.14 and failed.

**Comment by zhangzhengxin** [comment]
Same issue running with tensorflow 2.4.1. Any solution other than using Tensorflow v1.X

**Comment by Akila-Ayanthi** [comment]
Any solution other than degrading to Tensorflow v1.x?

**Comment by xmcs111** [comment]
the same q

**Comment by LioHaunt** [comment]
the same q TAT
