### ISSUE TITLE
how to solve the problem？

### ISSUE THREAD

**Issue by daojiaxu** [hanxiao/bert-as-service#591]
Traceback (most recent call last):
  File "d:\programdata\envs\python_3_6\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\envs\python_3_6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\envs\python_3_6\Scripts\bert-serving-start.exe\__main__.py", line 7, in <module>
  File "d:\programdata\envs\python_3_6\lib\site-packages\bert_serving\server\cli\__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "d:\programdata\envs\python_3_6\lib\site-packages\bert_serving\server\__init__.py", line 71, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: 'NoneType' object is not iterable

**Comment by endlesshh** [comment]
user tensorflow=1.15.0
