### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by Prithvi103** [hanxiao/bert-as-service#617]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 2019 server 10.0.17763
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14.0rc1
- Python version: 3.7.9
- `bert-as-service` version: 1.10.0
- GPU model and memory: None
- CPU model and memory: 8 GB RAM

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

bert-serving-start -model_dir C:\Users\sportsaiuser\Downloads\VideosProject\sportsBERT -num_worker=1 -max_seq_len=256 -cpu

Then this issue shows up:
WARNING:tensorflow:From C:\Users\sportsaiuser\AppData\Local\Programs\Python\Python37\lib\site-packages\bert_serving\server\helper.py:186: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From C:\Users\sportsaiuser\AppData\Local\Programs\Python\Python37\lib\site-packages\bert_serving\server\helper.py:186: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

I:[36mGRAPHOPT[0m:model config: C:\Users\sportsaiuser\Downloads\VideosProject\sportsBERT\bert_config.json
I:[36mGRAPHOPT[0m:checkpoint: C:\Users\sportsaiuser\Downloads\VideosProject\sportsBERT\bert_model.ckpt
E:[36mGRAPHOPT[0m:fail to optimize the graph!
Traceback (most recent call last):
  File "C:\Users\sportsaiuser\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\sportsaiuser\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sportsaiuser\AppData\Local\Programs\Python\Python37\Scripts\bert-serving-start.exe\__main__.py", line 7, in <module>
  File "C:\Users\sportsaiuser\AppData\Local\Programs\Python\Python37\lib\site-packages\bert_serving\server\cli\__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "C:\Users\sportsaiuser\AppData\Local\Programs\Python\Python37\lib\site-packages\bert_serving\server\__init__.py", line 71, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: cannot unpack non-iterable NoneType object

...

**Comment by Prithvi103** [comment]
I saw all similar posts and implemented all suggestions such as changing to absolute path, using the right tensorflow version (I have tried both 1.13.0rc1 and 1.14.0rc1).

This works on another machine which has GPU. Can someone please suggest something to fix this?

**Comment by Prithvi103** [comment]
I had the path wrong. smh
