### ISSUE TITLE
zmq.error.ZMQError: Operation not supported

### ISSUE THREAD

**Issue by JiaenLiu** [hanxiao/bert-as-service#625]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (WSL Ubuntu 18.04):
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.10.0
- Python version:3.6
- `bert-as-service` version: 1.10.0
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start -model_dir=/mnt/f/cased_L-12_H-768_A-12 -num_worker=4
```

Then this issue shows up:
```bash
bert-serving-start -model_dir=/mnt/f/cased_L-12_H-768_A-12 -num_worker=4
usage: /home/jiaenliu/anaconda3/envs/py36/bin/bert-serving-start -model_dir=/mnt/f/cased_L-12_H-768_A-12 -num_worker=4
                 ARG   VALUE
__________________________________________________
           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                cors = *
                 cpu = False
          device_map = []
       do_lower_case = True
  fixed_embed_length = False
                fp16 = False
 gpu_memory_fraction = 0.5
       graph_tmp_dir = None
    http_max_connect = 10
           http_port = None
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 25
           model_dir = /mnt/f/cased_L-12_H-768_A-12
no_position_embeddings = False
    no_special_token = False
          num_worker = 4
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556
       prefetch_size = 10
 priority_batch_size = 16
show_tokens_to_client = False
     tuned_model_dir = None
             verbose = False
                 xla = False

I:VENTILATOR:[__i:__i: 67]:freeze, optimize and export graph, could take a while...
I:GRAPHOPT:[gra:opt: 53]:model config: /mnt/f/cased_L-12_H-768_A-12/bert_config.json
I:GRAPHOPT:[gra:opt: 56]:checkpoint: /mnt/f/cased_L-12_H-768_A-12/bert_model.ckpt
I:GRAPHOPT:[gra:opt: 60]:build graph...
I:GRAPHOPT:[gra:opt:132]:load parameters from checkpoint...
I:GRAPHOPT:[gra:opt:136]:optimize...
I:GRAPHOPT:[gra:opt:144]:freeze...
I:GRAPHOPT:[gra:opt:149]:write graph to a tmp file: /tmp/tmparfnu0r5
I:VENTILATOR:[__i:__i: 75]:optimized graph is stored at: /tmp/tmparfnu0r5
I:VENTILATOR:[__i:_ru:129]:bind all sockets
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/jiaenliu/anaconda3/envs/py36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/jiaenliu/anaconda3/envs/py36/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 115, in run
    self._run()
  File "/home/jiaenliu/anaconda3/envs/py36/lib/python3.6/site-packages/zmq/decorators.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/jiaenliu/anaconda3/envs/py36/lib/python3.6/site-packages/zmq/decorators.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/jiaenliu/anaconda3/envs/py36/lib/python3.6/site-packages/zmq/decorators.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/jiaenliu/anaconda3/envs/py36/lib/python3.6/site-packages/bert_serving/server/zmq_decor.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/home/jiaenliu/anaconda3/envs/py36/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 131, in _run
    addr_front2sink = auto_bind(sink)
  File "/home/jiaenliu/anaconda3/envs/py36/lib/python3.6/site-packages/bert_serving/server/helper.py", line 203, in auto_bind
    socket.bind('ipc://{}'.format(tmp_dir))
  File "/home/jiaenliu/anaconda3/envs/py36/lib/python3.6/site-packages/zmq/sugar/socket.py", line 172, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Operation not supported
```

I have already tried the solution in this thread https://github.com/hanxiao/bert-as-service/issues/293 and it does not work for me.
...

**Comment by JiaenLiu** [comment]
I have figured it out. In the same way that I found in #293. I forget to make a dir which is called zmq.
