### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by abhishekkuber** [hanxiao/bert-as-service#630]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home, 64 bit OS
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.2
- Python version: 3.7.4
- `bert-as-service` version: 1.10.0
- GPU model and memory: NVIDIA GeForce MX150, 4096MB
- CPU model and memory: Intel Core i5-8250U Processor, 8GB

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start  -model_dir /cased_L-12_H-768_A-12/ -num_worker=4
```

and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
bc.encode()
```

Then this issue shows up:

...
When I go to start the server, the below issue pops up

g:\ana\lib\site-packages\bert_serving\server\helper.py:176: UserWarning: Tensorflow 2.3.2 is not tested! It may or may not work. Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/
  'Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/' % tf.__version__)
E:←[36mGRAPHOPT←[0m:fail to optimize the graph!
Traceback (most recent call last):
  File "g:\ana\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "g:\ana\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\ana\Scripts\bert-serving-start.exe\__main__.py", line 7, in <module>
  File "g:\ana\lib\site-packages\bert_serving\server\cli\__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "g:\ana\lib\site-packages\bert_serving\server\__init__.py", line 71, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: cannot unpack non-iterable NoneType object

Any kind of help will be appreciated, thanks

**Comment by NicoleJaneway** [comment]
Specify tensorflow==1.15.0 - that should fix it

**Comment by DmitryKey** [comment]
btw, that does not seem to work on Python 3.8.8

**Comment by TeTeTang** [comment]
Doesn't work on Python 3.8.8

**Comment by Razorblade2k** [comment]
I get same error with Python 3.6 and TF 1.15...
This is somehow broken.

**Comment by dleve123** [comment]
After banging my head against the wall for a while on this issue, was finally able to boot the server using:

- Python 3.6.16
- Tensorflow 1.15.0
- bert-as-service 1.10.0
- Linux 3.10 (RHEL)

```
$ uname -srv
Linux 3.10.0-862.2.3.el7.x86_64 #1 SMP Mon Apr 30 12:37:51 EDT 2018
```

from a new directory

```bash
$ conda create -n foo python=3.6
$ conda activate foo
$ pip install tensorflow==1.15.0
$ mkdir bert-params
$ wget https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip
$ cd ..
$ bert-serving-start -model_dir bert-params/cased_L-12_H-768_A-12/
```

It's possible that either/both of Python 3.6.16 and TF 1.15.0 are required, or that any 3.6.X and 1.15.X would work.

What I do know is that Python 3.7 with TF 1.15.X does _not_ work.

**Comment by zxhjames** [comment]
a nice solution,thank you

**Comment by zxhjames** [comment]
> After banging my head against the wall for a while on this issue, was finally able to boot the server using:
> 
> * Python 3.6.16
> * Tensorflow 1.15.0
> * bert-as-service 1.10.0
> * Linux 3.10 (RHEL)
> 
> ```
> $ uname -srv
> Linux 3.10.0-862.2.3.el7.x86_64 #1 SMP Mon Apr 30 12:37:51 EDT 2018
> ```
> 
> from a new directory
> 
> ```shell
> $ conda create -n foo python=3.6
> $ conda activate foo
> $ pip install tensorflow==1.15.0
> $ mkdir bert-params
> $ wget https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip
> $ cd ..
> $ bert-serving-start -model_dir bert-params/cased_L-12_H-768_A-12/
> ```
> 
> FWIW: Using miniconda meaning that a `conda create` does not install a lot of default packages.
> 
> It's possible that either/both of Python 3.6.16 and TF 1.15.0 are required, or that any 3.6.X and 1.15.X would work.
> 
> What I do know is that Python 3.7 with TF 1.15.X does _not_ work.

nice solutiion.thank you
