### ISSUE TITLE
ImportError: No module named 'tensorflow.python.platform'

### ISSUE THREAD

**Issue by dyf102** [hanxiao/bert-as-service#9]
```
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from service.server import BertServer
  File "/home/123/bert-as-service/service/server.py", line 12, in <module>
    import tensorflow as tf
  File "/home/123/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/123/.local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/123/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ImportError: No module named 'tensorflow.python.platform'
```
Thanks

**Comment by hanxiao** [comment]
check whether you fulfill the dependency requirements, i.e.
requirements.txt in this repo

it won’t work on python2 or tf <1.10

YUWEI <notifications@github.com>于2018年11月14日 周三下午11:43写道：

**Comment by dyf102** [comment]
Solved, thanks
